config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end

  get "/search", to: "searches#search"
  
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  get "tag_searches/search" => "tag_searches#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books , dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :group_users, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book =@books.created_last_week
    
    
    @currentUesrEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @users = User.all.order(created_at: :desc)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class="row">
  <% if current_user != user && !user.guest_user? %>
  　<td><%= render "relationships/btn", user: user, options: { class: ""} %></td>
  <% elsif current_user == user && !user.guest_user? %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    　<i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, url: user_path, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        
        <%= link_to "グループを作成する", new_group_path %>｜<%= link_to "グループ一覧", groups_path %>
        
        <%= render 'index',users: @users %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
  <div class="row">
    <h3>投稿数の前日比・前週比</h3>
      <div class="table_width">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿</th>
              <th>昨日の投稿</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td>
	            <td><%= @last_week_book.count %></td>
            <% if @last_week_book.count == 0 %>
	            <td>先週の投稿はなし</td>
            <% else %>
	            <td><% @the_week_before = @this_week_book.count / @last_week_book.count  %>
	            <%= (@the_week_before * 100).round %>%</td>
            <% end %>
            </tr>
          </tbody>
        </table>

        <table class="table">
          <thead>
            <tr>
             <th>今週の投稿</th>
             <th>先週の投稿</th>
             <th>比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td>
              <td><%= @last_week_book.count %></td>
               <% if @last_week_book.count == 0 %>
              <td>先週の投稿はなし</td>
               <% else %>
                 　<td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
                 　<%= (@the_week_before * 100).round %>%</td>
               <% end %>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
  <div class="row">
    <h4>7日間の投稿数</h4>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @books.created_6day_ago.count %></td>
            <td><%= @books.created_5day_ago.count %></td>
            <td><%= @books.created_4day_ago.count %></td>
            <td><%= @books.created_3day_ago.count %></td>
            <td><%= @books.created_2day_ago.count %></td>
            <td><%= @books.created_yesterday.count %></td>
            <td><%= @books.created_today.count %></td>
          </tr>
        </tbody>
      </table>

      <canvas id="postCountChart"></canvas>
<script>
  // ページが読み込まれたときの処理
  $(document).on('turbolinks:load', function() {
    // グラフを描画するためのCanvas要素を取得
    var ctx = document.getElementById("postCountChart");

    // Chart.jsを使ってグラフを作成
    var postCountChart = new Chart(ctx, {
      type: 'line', // ラインチャートを使用

      data: {
        // グラフのラベル（x軸の値）
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],

        datasets: [
          {
            // データセットのラベル
            label: '投稿した本の数',

            // データセットの値
            data: [
              <%= @books.created_6day_ago.count %>, // 6日前の投稿数
              <%= @books.created_5day_ago.count %>, // 5日前の投稿数
              <%= @books.created_4day_ago.count %>, // 4日前の投稿数
              <%= @books.created_3day_ago.count %>, // 3日前の投稿数
              <%= @books.created_2day_ago.count %>, // 2日前の投稿数
              <%= @books.created_yesterday.count %>, // 昨日の投稿数
              <%= @books.created_today.count %> // 今日の投稿数
            ],

            // グラフの線の色（緑）
            borderColor: "rgba(0, 255, 0, 1)",

            // グラフの背景色（透明）
            backgroundColor: "rgba(0, 0, 0, 0)",

            // グラフの曲線の滑らかさ（0から1の範囲で設定。数値が大きくなるほど曲線が滑らかになる）
            tension: 0.3
          }
        ],
      },

      options: {
        title: {
          // グラフのタイトル表示
          display: true,
          text: '7日間の投稿数の比較'
        },

        responsive: true, // グラフのレスポンシブデザインを有効化

        scales: {
          y: {
            // y軸（縦軸）の設定。設定しないと自動になるので書かなくても良い。
            suggestedMin: 0, // 最小値を0に設定
            suggestedMax: 10 // 最大値を10に設定
          },
        },
      }
    });
  });
</script>
  </div>
</div>